
all:  data.h errors.c helpers.c commands.c tables.c encode.c memory.c parse.c compiler.c
	gcc -ansi -Wall -pedantic data.h data.h errors.c helpers.c commands.c tables.c encode.c memory.c parse.c compiler.c -o compiler -lm

# clean:
# 	rm *.o all
# 	ls